# Generated by Django 2.1.5 on 2021-08-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yd_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_context', models.CharField(default='', max_length=500)),
                ('answer_context', models.CharField(default='', max_length=500)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Doctors')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='timetable',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Doctors'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'not available')], default=0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='t_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time_id',
            field=models.IntegerField(choices=[(1, 'Mon.'), (2, 'Tue.'), (3, 'Wed.'), (4, 'Thu.'), (5, 'Fri.')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Patients'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Patients'),
        ),
        migrations.AddField(
            model_name='booking',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Timetable'),
        ),
    ]
