# Generated by Django 2.1.5 on 2021-08-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_psw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50, null=True)),
                ('doctor_email', models.EmailField(max_length=254, unique=True)),
                ('doctor_psw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50, null=True)),
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('patient_age', models.IntegerField(null=True)),
                ('patient_gender', models.CharField(max_length=5, null=True)),
                ('patient_phone_num', models.CharField(max_length=20, null=True)),
                ('patient_psw', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('time_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
