# Generated by Django 2.1.5 on 2021-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yd_webapp', '0002_auto_20210803_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='slug',
            field=models.SlugField(),
        ),
    ]
