# Generated by Django 2.1.5 on 2021-08-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yd_webapp', '0003_auto_20210806_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='answer_context',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yd_webapp.Doctors'),
        ),
        migrations.AlterField(
            model_name='record',
            name='question_context',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
