# Generated by Django 2.1.5 on 2021-08-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yd_webapp', '0003_auto_20210805_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
